# Site
repository: c18gour/resume-cv
# favicon: images/favicon.ico

# Personal info
name: Χρυσούλα Γουρνάρα
title: Μαθηματικός
email: c18gour@ionio.gr
website: www.github.com/sproogen/resume-theme

# Social links
github_username:  xrys@
# pinterest_username: Xrysoulina

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Ονομάζομαι Χρυσούλα Γουρνάρα. Εχω σπουδάσει **Μαθηματικά** αλλά εργάζομαι 20 χρόνια στην **Εφορεία Αρχαιοτήτων Αχαΐας** ως Διοικητικός Υπάλληλος Π.Ε.
  Τα κυριότερα χαρακτηριστικά μου είναι: <mark>η επιμονή</mark> , <mark>η υπομονή</mark> και <mark>η συνεργατικότητα</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs

 Ιnterests
 Εθελόντρια στους Ολυμπιακούς αγώνες του 2004.(Ολυμπιακό Τουρνουά Ποδοσφαίρου στην Πάτρα στην ομάδα του συντονισμού των Φωτογράφων)
 Μέλος του Τζάζ φωνητικού σχήματος ‘VOCAL’, 
 Μαθήματα Κατασκευής Κοσμημάτων με ορείχαλκο ή ασήμι, 
 Ξένες γλώσσες, 
 Κινηματογράφος, Διάβασμα, Θέατρο και άλλες παντός είδους πολιτιστικές εκδηλώσεις, 
 Πεζοπορία, Ταξίδια, Φωτογραφία, 
 Περιηγήσεις και ταξίδια Αρχαιολογικού Ενδιαφέροντος, Επίσκεψη σε Μουσεία και Αρχαιολογικούς Χώρους   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
